"""Shared contracts package for inter-module DTOs."""

from .auth import AuthLoginRequest, AuthRegisterRequest, AuthStatusRead, AuthUserRead
from .billing import (
    AccountCreditsRead,
    AccountPlanRead,
    PaymentStatusRead,
    PixCheckoutRequest,
    PixCheckoutResponse,
    PixConfirmRequest,
    PlanEntitlementsRead,
    PlanRead,
    ResolvedEntitlements,
)
from .dashboard import (
    DashboardDistributionBucketRead,
    DashboardPriceHistoryPointRead,
    DashboardRankingItemRead,
    DashboardRankRead,
    DashboardSafetyHourBucketRead,
    ZoneDashboardAnalyticsRead,
    ZoneDashboardContextRead,
    ZoneDashboardEnvironmentRead,
    ZoneDashboardPriceRead,
    ZoneDashboardSafetyRead,
    ZoneFavoriteAnalyticsRead,
    ZoneFavoriteMetricsRead,
)
from .enums import JobState, JobType, JourneyState
from .jobs import JobCancelAccepted, JobCreate, JobEventRead, JobRead
from .journeys import JourneyCreate, JourneyRead, JourneyReferencePoint, JourneyUpdate
from .listings import (
    FavoriteListingCreate,
    FavoriteListingRead,
    FavoriteNoteUpdate,
    ListingAdRead,
    ListingCardRead,
    ListingPlatformVariantRead,
    ListingsRequestResult,
    ListingSnapshotRead,
    ManualFavoriteCreate,
    PriceRollupRead,
    PropertyRead,
    SearchAddressSuggestion,
    ZoneCacheStatusRead,
)
from .transport import TransportPointRead
from .zones import (
    FavoriteZoneCreate,
    FavoriteZoneMetricsSnapshot,
    FavoriteZoneNoteUpdate,
    FavoriteZonePayload,
    FavoriteZoneRead,
    FavoriteZoneTransportPoint,
    ZoneBadgeRead,
    ZoneJourneyRankRead,
    ZoneJourneyRankingsRead,
    ZoneListResponse,
    ZonePOIPointRead,
    ZonePriceSummaryRead,
    ZoneRead,
    ZoneSafetyIncidentCollectionRead,
    ZoneSafetyIncidentFeatureRead,
    ZoneSafetyIncidentGeometryRead,
    ZoneSafetyIncidentPropertiesRead,
)

__version__ = "0.1.0"

__all__ = [
    "AccountCreditsRead",
    "AccountPlanRead",
    "AuthLoginRequest",
    "AuthRegisterRequest",
    "AuthStatusRead",
    "AuthUserRead",
    "PaymentStatusRead",
    "PixCheckoutRequest",
    "PixCheckoutResponse",
    "PixConfirmRequest",
    "PlanEntitlementsRead",
    "PlanRead",
    "ResolvedEntitlements",
    "FavoriteListingCreate",
    "FavoriteListingRead",
    "FavoriteNoteUpdate",
    "FavoriteZoneCreate",
    "FavoriteZoneNoteUpdate",
    "FavoriteZoneMetricsSnapshot",
    "FavoriteZonePayload",
    "FavoriteZoneRead",
    "FavoriteZoneTransportPoint",
    "DashboardDistributionBucketRead",
    "DashboardPriceHistoryPointRead",
    "DashboardRankingItemRead",
    "DashboardRankRead",
    "DashboardSafetyHourBucketRead",
    "JobCancelAccepted",
    "JobCreate",
    "JobEventRead",
    "JobRead",
    "JobState",
    "JobType",
    "JourneyCreate",
    "JourneyRead",
    "JourneyReferencePoint",
    "JourneyState",
    "JourneyUpdate",
    "ListingAdRead",
    "ListingCardRead",
    "ListingPlatformVariantRead",
    "ListingsRequestResult",
    "ListingSnapshotRead",
    "ManualFavoriteCreate",
    "PriceRollupRead",
    "PropertyRead",
    "SearchAddressSuggestion",
    "TransportPointRead",
    "ZoneDashboardAnalyticsRead",
    "ZoneDashboardContextRead",
    "ZoneDashboardEnvironmentRead",
    "ZoneDashboardPriceRead",
    "ZoneDashboardSafetyRead",
    "ZoneFavoriteAnalyticsRead",
    "ZoneFavoriteMetricsRead",
    "ZoneBadgeRead",
    "ZoneCacheStatusRead",
    "ZoneJourneyRankRead",
    "ZoneJourneyRankingsRead",
    "ZonePOIPointRead",
    "ZonePriceSummaryRead",
    "ZoneRead",
    "ZoneListResponse",
    "ZoneSafetyIncidentCollectionRead",
    "ZoneSafetyIncidentFeatureRead",
    "ZoneSafetyIncidentGeometryRead",
    "ZoneSafetyIncidentPropertiesRead",
]
